Style rfp list

diff --git a/odo b/odo
--- a/odo
+++ b/odo
@@ -100,9 +100,25 @@ case "$1" in
             exit 1
         fi
 
+        echo -n "Copying schema from core..."
+        docker cp interview-core-1:/app/schema.json ./frontend/schema.json > /dev/null 2>&1
+        if [ $? -eq 0 ]; then
+            echo "done"
+        else
+            echo "error:"
+            echo "Failed to copy schema. Please check the container logs for more details."
+            exit 1
+        fi
+
         echo -n "Copying schema to frontend..."
-        cp ./core/schema.json ./frontend/schema.json
-        echo "done"
+        docker cp ./frontend/schema.json interview-frontend-1:/app/schema.json > /dev/null 2>&1
+        if [ $? -eq 0 ]; then
+            echo "done"
+        else
+            echo "error:"
+            echo "Failed to copy schema. Please check the container logs for more details."
+            exit 1
+        fi
 
         echo -n "Generating TypeScript types..."
         docker exec interview-frontend-1 sh -c "npm run types"
